# Generated by Django 3.2 on 2022-05-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('activity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjudicated_date', models.DateTimeField(null=True)),
                ('published_date', models.DateTimeField(null=True)),
                ('external_code', models.CharField(max_length=255)),
                ('category_code', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('mercadopublico_url', models.CharField(max_length=255)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
            ],
        ),
    ]
