# Generated by Django 3.2 on 2022-05-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='Contact',
            new_name='contact',
        ),
    ]
