# Generated by Django 3.2 on 2022-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contact_bidding_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='sended_to_ac',
            field=models.BooleanField(default=False),
        ),
    ]
