# Generated by Django 3.2 on 2022-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bidding_sended_to_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='external_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
